apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'expo-module-gradle-plugin'

group = 'com.webonone.smssender'
version = '1.0.0'

android {
  namespace 'expo.modules.smssender'
  defaultConfig {
    minSdkVersion safeExtGet('minSdkVersion', 24)
    compileSdkVersion safeExtGet('compileSdkVersion', 34)
    targetSdkVersion safeExtGet('targetSdkVersion', 34)
  }
}
