import { AI_CAPABILITY_VERSION, type ToolDefinition } from './capabilityTypes.js'

const KIND_ENUM = ['products', 'services', 'spaces'] as const
const CATALOG_KIND_ENUM = ['tags', 'units', 'attributes', 'products', 'services', 'spaces'] as const

const stringId = { type: 'string', minLength: 8, maxLength: 32 }
const kindSchema = { type: 'string', enum: [...KIND_ENUM] }
const catalogKindSchema = { type: 'string', enum: [...CATALOG_KIND_ENUM] }

function webononeTool(
  def: Omit<ToolDefinition, 'service' | 'capabilityVersion'>,
): ToolDefinition {
  return {
    ...def,
    service: 'webonone',
    capabilityVersion: AI_CAPABILITY_VERSION,
  }
}

export const webononeAiCapabilities: ToolDefinition[] = [
  webononeTool({
    name: 'search_public_catalog',
    description:
      'Search the public marketplace catalog of products, services, and spaces across companies. Use for website visitors and general discovery.',
    jsonSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {
        q: { type: 'string', description: 'Search query' },
        page: { type: 'integer', minimum: 1 },
        pageSize: { type: 'integer', minimum: 1, maximum: 50 },
      },
    },
    riskLevel: 'read',
    requiredRoles: ['guest', 'member', 'company_admin', 'super_admin'],
    requiredPermissions: ['ai:public_catalog:read'],
    auth: 'service_key',
    invoke: { method: 'GET', path: '/api/v1/internal/catalog/search' },
    viewPath: '/catalog/{kind}/{id}',
  }),
  webononeTool({
    name: 'search_company_catalog',
    description:
      'Search this company catalog (products, services, spaces, tags, units, or attributes).',
    jsonSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['kind'],
      properties: {
        kind: catalogKindSchema,
        q: { type: 'string', description: 'Optional name search' },
      },
    },
    riskLevel: 'read',
    requiredRoles: ['member', 'company_admin'],
    requiredPermissions: ['ai:catalog:read'],
    auth: 'user_jwt',
    invoke: { method: 'GET', path: '/api/v1/company/me/catalog/:kind' },
    viewPath: '/data/{kind}/{id}',
  }),
  webononeTool({
    name: 'get_catalog_item',
    description: 'Get one company catalog item by kind and id.',
    jsonSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['kind', 'id'],
      properties: {
        kind: catalogKindSchema,
        id: stringId,
      },
    },
    riskLevel: 'read',
    requiredRoles: ['member', 'company_admin'],
    requiredPermissions: ['ai:catalog:read'],
    auth: 'user_jwt',
    invoke: { method: 'GET', path: '/api/v1/company/me/catalog/:kind/:id' },
    viewPath: '/data/{kind}/{id}',
  }),
  webononeTool({
    name: 'create_catalog_item',
    description:
      'Create a custom company catalog product, service, or space. Do not use this to create a Data library tag — use create_data_tag. Fill kind, name, and a 1–3 sentence description with complete suggestions before asking the user to confirm. For services include timeMode (duration or window) and durationMinutes or startTime/endTime.',
    jsonSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['kind', 'name', 'description'],
      properties: {
        kind: kindSchema,
        name: { type: 'string', description: 'Display name of the catalog item.' },
        description: {
          type: 'string',
          description:
            'Required 1–3 sentence explanation of what this item is, who it is for, and when to use it. Suggest a complete value even if the user only gave a name.',
        },
        timeMode: {
          type: 'string',
          enum: ['duration', 'window'],
          description: 'Services only. duration for a fixed length; window for a start and end time.',
        },
        durationMinutes: {
          type: 'integer',
          minimum: 1,
          description: 'Services with timeMode duration. Suggest a typical length if the user did not specify.',
        },
        startTime: { type: 'string', description: 'HH:mm. Services with timeMode window only.' },
        endTime: { type: 'string', description: 'HH:mm. Services with timeMode window only.' },
      },
    },
    riskLevel: 'write',
    requiredRoles: ['company_admin'],
    requiredPermissions: ['ai:catalog:write'],
    auth: 'user_jwt',
    invoke: { method: 'POST', path: '/api/v1/company/me/catalog/:kind/custom' },
    viewPath: '/data/{kind}/{id}',
  }),
  webononeTool({
    name: 'update_catalog_item',
    description: 'Update a custom or forked company catalog item.',
    jsonSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['kind', 'id'],
      properties: {
        kind: kindSchema,
        id: stringId,
        name: { type: 'string' },
        description: { type: 'string' },
        timeMode: { type: 'string', enum: ['duration', 'window'] },
        durationMinutes: { type: 'integer', minimum: 1 },
        startTime: { type: 'string' },
        endTime: { type: 'string' },
      },
    },
    riskLevel: 'write',
    requiredRoles: ['company_admin'],
    requiredPermissions: ['ai:catalog:write'],
    auth: 'user_jwt',
    invoke: { method: 'PATCH', path: '/api/v1/company/me/catalog/:kind/:id' },
    viewPath: '/data/{kind}/{id}',
  }),
  webononeTool({
    name: 'delete_catalog_item',
    description: 'Delete a company catalog item. Destructive; requires user confirmation.',
    jsonSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['kind', 'id'],
      properties: {
        kind: catalogKindSchema,
        id: stringId,
      },
    },
    riskLevel: 'destructive',
    requiredRoles: ['company_admin'],
    requiredPermissions: ['ai:catalog:write'],
    auth: 'user_jwt',
    invoke: { method: 'DELETE', path: '/api/v1/company/me/catalog/:kind/:id' },
  }),
  webononeTool({
    name: 'link_catalog_item',
    description:
      'Link a Data library entity into this company catalog without copying fields. Requires a company-admin session.',
    jsonSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['kind', 'libraryEntityId'],
      properties: {
        kind: catalogKindSchema,
        libraryEntityId: stringId,
      },
    },
    riskLevel: 'write',
    requiredRoles: ['company_admin'],
    requiredPermissions: ['ai:catalog:write'],
    auth: 'user_jwt',
    invoke: { method: 'POST', path: '/api/v1/company/me/catalog/:kind/link' },
    viewPath: '/data/{kind}/{id}',
  }),
  webononeTool({
    name: 'from_library_catalog',
    description:
      'Add a Data library entity to this company catalog as linked or forked. Forked mode requires payload.',
    jsonSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['kind', 'libraryEntityId', 'mode'],
      properties: {
        kind: catalogKindSchema,
        libraryEntityId: stringId,
        mode: { type: 'string', enum: ['linked', 'forked'] },
        payload: { type: 'object', additionalProperties: true },
      },
    },
    riskLevel: 'write',
    requiredRoles: ['company_admin'],
    requiredPermissions: ['ai:catalog:write'],
    auth: 'user_jwt',
    invoke: { method: 'POST', path: '/api/v1/company/me/catalog/:kind/from-library' },
    viewPath: '/data/{kind}/{id}',
  }),
  webononeTool({
    name: 'fork_catalog_item',
    description: 'Fork a linked company catalog item into an editable company-owned copy.',
    jsonSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['kind', 'id', 'payload'],
      properties: {
        kind: catalogKindSchema,
        id: stringId,
        payload: { type: 'object', additionalProperties: true },
      },
    },
    riskLevel: 'write',
    requiredRoles: ['company_admin'],
    requiredPermissions: ['ai:catalog:write'],
    auth: 'user_jwt',
    invoke: { method: 'POST', path: '/api/v1/company/me/catalog/:kind/:id/fork' },
    viewPath: '/data/{kind}/{id}',
  }),
  webononeTool({
    name: 'list_events',
    description: 'List company calendar events and appointments.',
    jsonSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {
        q: { type: 'string' },
        from: { type: 'string', description: 'YYYY-MM-DD' },
        to: { type: 'string', description: 'YYYY-MM-DD' },
        page: { type: 'integer', minimum: 1 },
        pageSize: { type: 'integer', minimum: 1, maximum: 100 },
      },
    },
    riskLevel: 'read',
    requiredRoles: ['member', 'company_admin'],
    requiredPermissions: ['ai:events:read'],
    auth: 'user_jwt',
    invoke: { method: 'GET', path: '/api/v1/company/events' },
    viewPath: '/calendar/events/{id}',
  }),
  webononeTool({
    name: 'get_event',
    description: 'Get one company calendar event by id.',
    jsonSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['id'],
      properties: { id: stringId },
    },
    riskLevel: 'read',
    requiredRoles: ['member', 'company_admin'],
    requiredPermissions: ['ai:events:read'],
    auth: 'user_jwt',
    invoke: { method: 'GET', path: '/api/v1/company/events/:id' },
    viewPath: '/calendar/events/{id}',
  }),
  webononeTool({
    name: 'create_event',
    description:
      'Create a company calendar event for a service and staff member. Recurrence defaults to weekly.',
    jsonSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['service_id', 'staff_id', 'starts_on', 'recurrence_until'],
      properties: {
        service_id: { ...stringId, description: 'Existing company service id. Never invent ids.' },
        staff_id: { ...stringId, description: 'Existing company staff id. Never invent ids.' },
        attendee_display_name: {
          type: 'string',
          description: 'Optional attendee name. Only set when the user provided a name. Do not invent people.',
        },
        attendee_email: {
          type: 'string',
          description: 'Optional attendee email. Only set when the user provided an email. Never invent emails.',
        },
        space_id: { ...stringId, description: 'Existing company space id. Never invent ids.' },
        starts_on: { type: 'string', description: 'YYYY-MM-DD' },
        start_time: { type: 'string', description: 'HH:mm for duration services' },
        weekdays: { type: 'array', items: { type: 'integer', minimum: 0, maximum: 6 } },
        recurrence: {
          type: 'string',
          enum: ['none', 'weekly', 'biweekly', 'monthly_first_week', 'monthly_by_date'],
        },
        recurrence_until: { type: 'string', description: 'YYYY-MM-DD' },
      },
    },
    riskLevel: 'write',
    requiredRoles: ['company_admin'],
    requiredPermissions: ['ai:events:write'],
    auth: 'user_jwt',
    invoke: { method: 'POST', path: '/api/v1/company/events' },
    viewPath: '/calendar/events/{id}',
  }),
  webononeTool({
    name: 'update_event',
    description: 'Update a company calendar event.',
    jsonSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['id'],
      properties: {
        id: stringId,
        service_id: stringId,
        staff_id: stringId,
        attendee_display_name: { type: 'string' },
        attendee_email: { type: 'string' },
        space_id: stringId,
        starts_on: { type: 'string' },
        start_time: { type: 'string' },
        weekdays: { type: 'array', items: { type: 'integer', minimum: 0, maximum: 6 } },
        recurrence: {
          type: 'string',
          enum: ['none', 'weekly', 'biweekly', 'monthly_first_week', 'monthly_by_date'],
        },
        recurrence_until: { type: 'string' },
      },
    },
    riskLevel: 'write',
    requiredRoles: ['company_admin'],
    requiredPermissions: ['ai:events:write'],
    auth: 'user_jwt',
    invoke: { method: 'PATCH', path: '/api/v1/company/events/:id' },
    viewPath: '/calendar/events/{id}',
  }),
  webononeTool({
    name: 'delete_event',
    description: 'Delete a company calendar event. Destructive; requires user confirmation.',
    jsonSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['id'],
      properties: { id: stringId },
    },
    riskLevel: 'destructive',
    requiredRoles: ['company_admin'],
    requiredPermissions: ['ai:events:write'],
    auth: 'user_jwt',
    invoke: { method: 'DELETE', path: '/api/v1/company/events/:id' },
  }),
  webononeTool({
    name: 'list_staff',
    description: 'List company staff members.',
    jsonSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {},
    },
    riskLevel: 'read',
    requiredRoles: ['member', 'company_admin'],
    requiredPermissions: ['ai:staff:read'],
    auth: 'user_jwt',
    invoke: { method: 'GET', path: '/api/v1/company/staff' },
    viewPath: '/staff/{id}',
  }),
  webononeTool({
    name: 'get_staff',
    description: 'Get one company staff member by id.',
    jsonSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['id'],
      properties: { id: stringId },
    },
    riskLevel: 'read',
    requiredRoles: ['member', 'company_admin'],
    requiredPermissions: ['ai:staff:read'],
    auth: 'user_jwt',
    invoke: { method: 'GET', path: '/api/v1/company/staff/:id' },
    viewPath: '/staff/{id}',
  }),
  webononeTool({
    name: 'create_staff',
    description:
      'Add a staff member. schedule must include all 7 days (day_of_week 0-6) with at least one working day.',
    jsonSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['user_id', 'display_name', 'schedule'],
      properties: {
        user_id: { ...stringId, description: 'Existing Identity user id to add as staff. Never invent ids.' },
        display_name: { type: 'string', description: 'Staff display name as shown in the company calendar.' },
        email: { type: 'string', description: 'Optional. Only set when the user provided an email. Never invent emails.' },
        schedule: {
          type: 'array',
          minItems: 7,
          maxItems: 7,
          items: {
            type: 'object',
            required: ['day_of_week', 'is_working'],
            properties: {
              day_of_week: { type: 'integer', minimum: 0, maximum: 6 },
              is_working: { type: 'boolean' },
              start_time: { type: 'string' },
              end_time: { type: 'string' },
            },
          },
        },
      },
    },
    riskLevel: 'write',
    requiredRoles: ['company_admin'],
    requiredPermissions: ['ai:staff:write'],
    auth: 'user_jwt',
    invoke: { method: 'POST', path: '/api/v1/company/staff' },
    viewPath: '/staff/{id}',
  }),
  webononeTool({
    name: 'update_staff',
    description: 'Update a company staff member.',
    jsonSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['id'],
      properties: {
        id: stringId,
        display_name: { type: 'string' },
        email: { type: 'string' },
        schedule: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              day_of_week: { type: 'integer', minimum: 0, maximum: 6 },
              is_working: { type: 'boolean' },
              start_time: { type: 'string' },
              end_time: { type: 'string' },
            },
          },
        },
      },
    },
    riskLevel: 'write',
    requiredRoles: ['company_admin'],
    requiredPermissions: ['ai:staff:write'],
    auth: 'user_jwt',
    invoke: { method: 'PATCH', path: '/api/v1/company/staff/:id' },
    viewPath: '/staff/{id}',
  }),
  webononeTool({
    name: 'delete_staff',
    description: 'Remove a company staff member. Destructive; requires user confirmation.',
    jsonSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['id'],
      properties: { id: stringId },
    },
    riskLevel: 'destructive',
    requiredRoles: ['company_admin'],
    requiredPermissions: ['ai:staff:write'],
    auth: 'user_jwt',
    invoke: { method: 'DELETE', path: '/api/v1/company/staff/:id' },
  }),
  webononeTool({
    name: 'list_staff_leaves',
    description:
      'List leave records for a company staff member. Use list_staff first to resolve staff id. Optional status filter: all, pending, approved, rejected.',
    jsonSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['id'],
      properties: {
        id: { ...stringId, description: 'Company staff id from list_staff or get_staff.' },
        page: { type: 'integer', minimum: 1, description: 'Page number (default 1).' },
        pageSize: { type: 'integer', minimum: 1, maximum: 100, description: 'Page size (default 12).' },
        status: {
          type: 'string',
          enum: ['all', 'pending', 'approved', 'rejected'],
          description: 'Filter by leave status.',
        },
      },
    },
    riskLevel: 'read',
    requiredRoles: ['member', 'company_admin'],
    requiredPermissions: ['ai:staff:read'],
    auth: 'user_jwt',
    invoke: { method: 'GET', path: '/api/v1/company/staff/:id/leaves' },
    viewPath: '/staff/{id}?tab=leaves',
  }),
  webononeTool({
    name: 'create_staff_leave',
    description:
      'Add leave for a staff member. Suggest leave_type (annual, sick, casual, unpaid, other), start_date and end_date (YYYY-MM-DD), and optional reason. Staff-created leaves start pending; company owner-created leaves are approved immediately. Use list_staff to resolve staff id.',
    jsonSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['id', 'leave_type', 'start_date', 'end_date'],
      properties: {
        id: { ...stringId, description: 'Company staff id from list_staff.' },
        leave_type: {
          type: 'string',
          enum: ['annual', 'sick', 'casual', 'unpaid', 'other'],
          description: 'Leave category.',
        },
        start_date: { type: 'string', description: 'Start date YYYY-MM-DD.' },
        end_date: { type: 'string', description: 'End date YYYY-MM-DD (on or after start).' },
        reason: { type: 'string', description: 'Optional reason for leave.' },
      },
    },
    riskLevel: 'write',
    requiredRoles: ['member', 'company_admin'],
    requiredPermissions: ['ai:staff:write'],
    auth: 'user_jwt',
    invoke: { method: 'POST', path: '/api/v1/company/staff/:id/leaves' },
    viewPath: '/staff/{id}?tab=leaves',
    argCompletion: {
      allowedKeys: ['id', 'leave_type', 'start_date', 'end_date', 'reason'],
    },
  }),
  webononeTool({
    name: 'approve_staff_leave',
    description:
      'Approve a pending staff leave. Company owner only. Requires staff id and leave id from list_staff_leaves.',
    jsonSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['id', 'leaveId'],
      properties: {
        id: { ...stringId, description: 'Company staff id.' },
        leaveId: { ...stringId, description: 'Leave record id from list_staff_leaves.' },
      },
    },
    riskLevel: 'write',
    requiredRoles: ['company_admin'],
    requiredPermissions: ['ai:staff:write'],
    auth: 'user_jwt',
    invoke: { method: 'POST', path: '/api/v1/company/staff/:id/leaves/:leaveId/approve' },
    viewPath: '/staff/{id}?tab=leaves',
  }),
  webononeTool({
    name: 'reject_staff_leave',
    description:
      'Reject a pending staff leave. Company owner only. Requires staff id and leave id from list_staff_leaves.',
    jsonSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['id', 'leaveId'],
      properties: {
        id: { ...stringId, description: 'Company staff id.' },
        leaveId: { ...stringId, description: 'Leave record id from list_staff_leaves.' },
      },
    },
    riskLevel: 'write',
    requiredRoles: ['company_admin'],
    requiredPermissions: ['ai:staff:write'],
    auth: 'user_jwt',
    invoke: { method: 'POST', path: '/api/v1/company/staff/:id/leaves/:leaveId/reject' },
    viewPath: '/staff/{id}?tab=leaves',
  }),
  webononeTool({
    name: 'get_my_company',
    description: 'Get the signed-in user company profile and membership.',
    jsonSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {},
    },
    riskLevel: 'read',
    requiredRoles: ['member', 'company_admin'],
    requiredPermissions: ['ai:company:read'],
    auth: 'user_jwt',
    invoke: { method: 'GET', path: '/api/v1/company/me' },
    viewPath: '/settings/basic',
  }),
  webononeTool({
    name: 'update_company',
    description:
      'Update the active company profile (name, description, contact, address). Company id comes from the session, not from arguments.',
    jsonSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {
        name: { type: 'string' },
        description: { type: 'string' },
        contactEmail: { type: 'string' },
        contactPhone: { type: 'string' },
        addressLine1: { type: 'string' },
        city: { type: 'string' },
        country: { type: 'string' },
      },
    },
    riskLevel: 'write',
    requiredRoles: ['company_admin'],
    requiredPermissions: ['ai:company:write'],
    auth: 'user_jwt',
    invoke: { method: 'PATCH', path: '/api/v1/company/:companyId' },
  }),
  webononeTool({
    name: 'list_pending_companies',
    description: 'List companies waiting for super-admin approval.',
    jsonSchema: { type: 'object', additionalProperties: false, properties: {} },
    riskLevel: 'read',
    requiredRoles: ['super_admin'],
    requiredPermissions: ['ai:company:admin'],
    auth: 'user_jwt',
    invoke: { method: 'GET', path: '/api/v1/company/admin/pending' },
    viewPath: '/settings/companies/{id}',
  }),
  webononeTool({
    name: 'list_all_companies',
    description: 'List all companies for super-admin review.',
    jsonSchema: { type: 'object', additionalProperties: false, properties: {} },
    riskLevel: 'read',
    requiredRoles: ['super_admin'],
    requiredPermissions: ['ai:company:admin'],
    auth: 'user_jwt',
    invoke: { method: 'GET', path: '/api/v1/company/admin/companies' },
    viewPath: '/settings/companies/{id}',
  }),
  webononeTool({
    name: 'approve_company',
    description: 'Approve a pending company. Super-admin only; requires confirmation.',
    jsonSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['id'],
      properties: { id: stringId },
    },
    riskLevel: 'write',
    requiredRoles: ['super_admin'],
    requiredPermissions: ['ai:company:admin'],
    auth: 'user_jwt',
    invoke: { method: 'POST', path: '/api/v1/company/admin/:id/approve' },
    viewPath: '/settings/companies/{id}',
  }),
  webononeTool({
    name: 'set_company_status',
    description: 'Set a company status to pending, approved, or rejected. Super-admin only.',
    jsonSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['id', 'status'],
      properties: {
        id: stringId,
        status: { type: 'string', enum: ['pending', 'approved', 'rejected'] },
      },
    },
    riskLevel: 'write',
    requiredRoles: ['super_admin'],
    requiredPermissions: ['ai:company:admin'],
    auth: 'user_jwt',
    invoke: { method: 'PATCH', path: '/api/v1/company/admin/:id/status' },
    viewPath: '/settings/companies/{id}',
  }),
]
